[workspace]
members = [
  "src/canister/configuration",
  "src/canister/data_backup",
  "src/canister/individual_user_template",
  "src/canister/post_cache/",
  "src/canister/user_index",
  "src/lib/integration_tests",
  "src/lib/shared_utils",
  "src/lib/test_utils",
]

[workspace.dependencies]
candid = "0.8.4"
ciborium = "0.2.1"
ic-cdk = "0.8.1"
ic-cdk-timers = "0.2.0"
ic-stable-structures = "0.5.6"
ic-test-state-machine-client = "2.2.1"
rmp-serde = "1.1.1"
serde = "1.0.183"
shared_utils = { path = "./src/lib/shared_utils" }
test_utils = { path = "./src/lib/test_utils" }